### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by sergeevabc** [ychclone/blink#1]
Windows 7, Blink 1.5.1

```
$ blink.exe
```

![](https://user-images.githubusercontent.com/373718/113380545-0c79ec00-936c-11eb-989f-8217d1d1f672.png) ![](https://user-images.githubusercontent.com/373718/113380546-0d128280-936c-11eb-803e-7e08c12d45eb.png)

**Comment by ychclone** [comment]
The windows version for v1.5.1 has been updated to fix the qt dependencies problem

https://github.com/ychclone/blink/releases/tag/1.5.1
